export const ENDPOINT = {
  SIGNUP: "auth/signup",
  LOGIN: "auth/signin",
  FORGOTPASSWORD: "auth/forgot-password",
  CONFIRMPASSWORD: "auth/confirm-password",
  USERME: "user/me",
  DEPLOYMENTSDEFAULT: "deployments/default",
  DEPLOYMENTSSTACKCONNECTOR: "deployments/stackConnector",
  TRAFFICACTIVITYLOGS: "logs",
  COLUMNVISIBILITY: "columns/trafficActivity",
  CLOUDCONNECTORPOLICY: "cloud-connector/policy",
  CLOUDCONNECTOR: "cloud-connector",
  SECURITYPROFILE: "security-profile",
  GETDESTINATION: "insights",
  STACKCONNECTIVITY: "stack-connector",
  DEPLOYSTACK: "infra/deploy",
  EMAILCODE: "infra/sendTwoFaEmail",
  DELETEdEPLOYEDSTACK: "infra/destroy",
  GETSTACKSOURCES: "stack-connector/vpc",
  GETSTACKSUBNETS: "stack-connector/subnet",
  ADDSTACKCONNECT: "stack-connector/add",
  DASHBOARDPOSTURE: "posture",
};
